/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CrowdsaleContract extends Truffle.Contract<CrowdsaleInstance> {
  "new"(
    rateOfToken: number | BN | string,
    walletAddress: string,
    tokenToSend: string,
    meta?: Truffle.TransactionDetails
  ): Promise<CrowdsaleInstance>;
}

export interface TokensPurchased {
  name: "TokensPurchased";
  args: {
    purchaser: string;
    beneficiary: string;
    value: BN;
    amount: BN;
    0: string;
    1: string;
    2: BN;
    3: BN;
  };
}

type AllEvents = TokensPurchased;

export interface CrowdsaleInstance extends Truffle.ContractInstance {
  /**
   */
  token(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   */
  wallet(txDetails?: Truffle.TransactionDetails): Promise<string>;

  /**
   */
  rate(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   */
  weiRaised(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  /**
   * low level token purchase ***DO NOT OVERRIDE*** This function has a non-reentrancy guard, so it shouldn't be called by another `nonReentrant` function.
   * @param beneficiary Recipient of the token purchase
   */
  buyTokens: {
    (beneficiary: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      beneficiary: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      beneficiary: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      beneficiary: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    /**
     */
    token(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     */
    wallet(txDetails?: Truffle.TransactionDetails): Promise<string>;

    /**
     */
    rate(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     */
    weiRaised(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    /**
     * low level token purchase ***DO NOT OVERRIDE*** This function has a non-reentrancy guard, so it shouldn't be called by another `nonReentrant` function.
     * @param beneficiary Recipient of the token purchase
     */
    buyTokens: {
      (beneficiary: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        beneficiary: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        beneficiary: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        beneficiary: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
