/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CrowdsaleContract } from "./Crowdsale";
import { ERC20Contract } from "./ERC20";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { KYCValidationContract } from "./KYCValidation";
import { MigrationsContract } from "./Migrations";
import { SatiTokenContract } from "./SatiToken";
import { SatiTokenSaleContract } from "./SatiTokenSale";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Crowdsale"): CrowdsaleContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "KYCValidation"): KYCValidationContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "SatiToken"): SatiTokenContract;
      require(name: "SatiTokenSale"): SatiTokenSaleContract;
    }
  }
}

export { CrowdsaleContract, CrowdsaleInstance } from "./Crowdsale";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { KYCValidationContract, KYCValidationInstance } from "./KYCValidation";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { SatiTokenContract, SatiTokenInstance } from "./SatiToken";
export { SatiTokenSaleContract, SatiTokenSaleInstance } from "./SatiTokenSale";
